version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db_v2
    env_file: ".env"
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: wallet_app
    depends_on:
      - db
    env_file: ".env"
    ports:
      - "8002:8000"

volumes:
  db_data:
