version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db_v2
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: wallet_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wallet_user
      DB_PASSWORD: wallet_pass
      DB_NAME: wallet_db
    ports:
      - "8002:8000"

volumes:
  db_data:
